### ISSUE TITLE
Multi-monitor setup doesn't appear to work when displays are set above/below

### ISSUE THREAD

**Issue by drod3763** [croian/mouseless-issues#5] opened 2024-12-10 23:41 UTC
### mouseless version

v0.2.0

### macOS version

14.6.1

### Other system input apps

See below for that information

### What happened?

My displays are oriented as per the below:
<img width="359" alt="Screenshot 2024-12-10 at 6 37 59 PM" src="https://github.com/user-attachments/assets/068c23fc-731d-4b3c-9b14-6bcfbba3fe71">

When I move into  the large upper display, all mouse clicks are diverted to the display just below it, my Macbook. The same thing happens when I move into the two displays on the right side. Clicks on the bottom display register but clicks on the top are eaten by the one below it.

My accessibility apps are as below:
<img width="476" alt="Screenshot 2024-12-10 at 6 41 03 PM" src="https://github.com/user-attachments/assets/3c0ced3a-e5ca-4bed-a03e-c1d8da56d4de">

My automation apps are as per the below:
<img width="479" alt="Screenshot 2024-12-10 at 6 41 14 PM" src="https://github.com/user-attachments/assets/cf4d2f42-1de8-4999-bb72-0ea2edd47e88">

### Steps to Reproduce

1. Have more than one display setup.
2. Orient them so that one is above the other
3. Open the overlay, move it into the upper display
4. Click something obvious
Expected: Click registers in the upper display
Actual: Click registers on the lower display

**Comment by croian** [comment] 2024-12-11 01:27
Thank you for the detailed report, @drod3763!  I can see that it definitely doesn't handle vertically arranged monitors well -- in my testing, the overlay doesn't move between them when I press the hotkey.  Will investigate and prioritize!

**Comment by nickyhuyskens** [comment] 2024-12-11 09:04
it doesnt work on my horizontal monitors either, only my main monitor gets the grid.
I am using aerospace though, maybe thats the issue for me?

**Comment by drod3763** [comment] 2024-12-11 17:09
> it doesnt work on my horizontal monitors either, only my main monitor gets the grid. I am using aerospace though, maybe thats the issue for me?

When the grid is open, does pressing Shift not move the grid to the second display?

**Comment by zain-ak** [comment] 2024-12-11 18:13
> it doesnt work on my horizontal monitors either, only my main monitor gets the grid. I am using aerospace though, maybe thats the issue for me?

Same-ish

I'm using an external keyboard so to see the grid I sometimes need to tap the key multiple times. 

The bigger issue, however, on a horizontal layout when I've specified a place to click, it seems to be registering the click elsewhere on the page, usually in line horizontally, but lower vertically.

Let me know if any additional info would be helpful!

**Comment by S4more** [comment] 2024-12-11 23:19
Same here!

**Comment by croian** [comment] 2024-12-11 23:23
Update: I've fixed both 1) the switch_monitor action, and 2) the click position on secondary monitors positioned with a non-zero y-offset -- but only when the monitors have the same scaled resolution

So I'm onto fixing the click position when they have different resolutions.

It seems possible (and I hope) that this will fix the issues people are having with multiple monitors generally.

**Comment by drod3763** [comment] 2024-12-12 00:11
The fix for different resolutions is what I need unfortunately.

**Comment by croian** [comment] 2024-12-12 02:44
Got it figured out!  Apparently NSScreen.mainScreen() does *not* mean "main display" lol (instead means current/focused).  Going to try to squeeze in one or two more important fixes and push a patch version tonight or tomorrow.

**Comment by senritsu** [comment] 2024-12-12 07:11
Same-ish issue here, different resolutions between laptop and external monitors, glad to see it's already being worked on :) 

On topic of multi-monitor and switching, although I couldn't really play around much due to the resolution issue, it seems a bit tedious to switch one-by-one, and additionally LShift for me cycles incorrectly (starting at the laptop right-most, LShift goes to my left-most screen, LShift again goes to the center screen, but as macOS itself frequently screws up multi-monitor setups I'm not too surprised). 

Have you considered adding some option to use a third letter input or similar to directly jump to a certain screen? Maybe something like "current screen" doesn't need anything and works just like now, but to jump to any other screen theres a one-tap input, maybe numerics or something? Just a 15 second idea, so take it with a grain of salt.

**Comment by lhk** [comment] 2024-12-12 07:48
I absolutely love the idea of Mouseless. And after watching the demo video I downloaded the trial immediately.

Well, I do have a multi monitor setup. Two external monitors side-by-side in the office, one external monitor at home. Plus a macbook that's always below the monitors. And the monitors do have different resolutions.
The bug discussed here keeps me from using mouseless. Would be great to see a fix.

**Comment by S4more** [comment] 2024-12-12 14:38
I would love for the overlay to come-up where my cursor is. If I'm integrating with a window manager such as AeroSpace, my mouse will often follow focus of the workspace I'm on. E.g.: 
- I switch to workspace S using Aerospace (where my Slack is - Monitor 1). My mouse goes to the slack window
- Pressing Alt will open the overlay on monitor 1.
- I change to workspace I (where me IDE is - Monitor 2). My mouse goes to the IDE
- Pressing At will open the overlay on monitor 2

**Comment by croian** [comment] 2024-12-12 16:54
@S4more awesome idea!  will add options for which monitor the overlay appears on in a future release, and I'll make that one of them

**Comment by DomKalinowski** [comment] 2024-12-12 21:52
I fixed this issue whilst writing this comment by centring both monitors, but it still might be useful:

<img width="605" alt="image" src="https://github.com/user-attachments/assets/2007d2f0-c339-41dd-a03b-afc205029ea4" />

**My current config customisations:**
I've set this up after following the steps below.
<img width="482" alt="image" src="https://github.com/user-attachments/assets/90a00935-7b99-42d5-b055-7fc42a9314f9" />


**Setup:**
MacOS: 15.2 (24C101)
Monitors:
- Build-in 14": 1800x1169 (main)
- Sony TY 55": 3840x2160

The remaining issues are moving the cursor between screens and being unable to click on the external screen, which I may need to open separately later.
---

Cycling between screens worked only once (from the build-in to the external) for the asymmetric arrangement.

<img width="607" alt="image" src="https://github.com/user-attachments/assets/ed00dedf-f929-45d5-9296-5a8634f783c9" />

Steps to reproduce:
1. Open the default overlay on the Build-in screen
2. Switch to the external monitor above
3. Click right alt to hide the overlay
4. Change the **number of columns** and **rows** to 35
5. Append `0123456789` to the `mouse action keys`
6. Save config from the toolbar
7. Open overlay (should open in the external monitor)
8. Try to switch the monitor using either of the shift keys

This will result only in blinking, but the overlay will stay on the external monitor.

**Comment by croian** [comment] 2024-12-13 12:29
@DomKalinowski i'm too tired to parse your comment right now 😅 so i'll come back and read it later, going to close the issue now that v0.2.1 is released, but can re-open / follow up if needed

**Comment by croian** [comment] 2024-12-13 12:30
🎉 released in v0.2.1 🎉

**Closed by croian** 2024-12-13 12:30 UTC
Labels: bug, fixed, pending release
