### ISSUE TITLE
mouse doesn't stay at place

### ISSUE THREAD

**Issue by tesspilot** [croian/mouseless-issues#15] opened 2024-12-12 13:43 UTC
### mouseless version

0.20

### macOS version

sequioa 15.1

### Other system input apps

no

### What happened?

after shortcut the mouse always goes to the bottom left corner.

### Steps to Reproduce

I have no idea?

**Comment by croian** [comment] 2024-12-12 17:02
hi @tesspilot, this is a feature not a bug 😅 it can be changed via the "Hide cursor on click" option in the config editor (press tab while overlay is up to bring it up)

i may set the default for this option to false in the patch release i'm pushing out later today, as well as make some changes to the welcome screen to make it clearer how to configure these options.

glad you raised the issue, thanks!

**Comment by croian** [comment] 2024-12-13 12:37
released in v0.2.1

i set the new default to false so first time users will now be greeted with more intuitive behavior, and the welcome screen guides them explicitly on how to view/change program options

thanks again for raising this!

**Closed by croian** 2024-12-13 12:37 UTC
Labels: bug, fixed
