### ISSUE TITLE
Vertical Monitor UI Squished and Grid Quirks

### ISSUE THREAD

**Issue by thorivarnj** [croian/mouseless-issues#6] opened 2024-12-11 11:00 UTC
### mouseless version

v0.2.0

### macOS version

Sequoia 15.1.1

### What happened?

When using mouseless on a horizontal display — in my case 1440x2560 — the letters are overlapping making it hard to read. 

The grid that is displayed behind the letter combinations is also not the same as when I choose a letter combination, e.g. the grid behind the `SF` combination is very tiny compared to when I select the `SF` combination. The smaller grid behind the combinations make it even harder to read.

I guess this could be filed as either bug or enhancement, I am filing as bug since this does not seem intentional. 

### Steps to Reproduce

Open the mouseless overlay on a horizontal display with the resolution of 1440x2560.

**Comment by croian** [comment] 2024-12-11 15:53
Thank you for this, @thorivarnj!  I edited the title to say to "Vertical monitor", as I assume that's what was intended, please correct me if I'm wrong.

I can definitely see some bugginess with the sub-grid on vertical monitors (i.e. dimensions are flipped in the "always-on" subgrid).  Will fix that.

I can also see the readability issues with the letters overlapping or squished close together.  I'm thinking the solution for this will be something like a `cell_char_arrangement` option, with `horizontal`, `vertical`, and `auto` (with `auto` arranging them vertically only when the cells are taller than they are wide).

**Alleviation in the meantime**: for those experiencing this issue, I'd recommend adjusting some settings until fixes/improvements are in: turn off `Always show subgrid`, decrease `font size multiplier` and perhaps increase `sub-grid font size multipler`.

**Comment by croian** [comment] 2024-12-19 04:16
@thorivarnj (and any other watchers), just a heads up that I'm closing this one in favor of #49.  will post progress updates there.

**Closed by croian** 2024-12-19 04:16 UTC
Labels: bug

**Comment by croian** [comment] 2024-12-21 22:18
@thorivarnj [v0.2.2-preview.1](https://github.com/croian/mouseless-issues/releases/tag/v0.2.2-preview.1) has been uploaded which addresses this issue.  Any feedback/evaluation is definitely appreciated!
