### ISSUE TITLE
Installable via homebrew

### ISSUE THREAD

**Issue by ajjaic** [croian/mouseless-issues#55] opened 2024-12-15 02:57 UTC
### Problem Description

Mouseless is already a significant productivity-enhancing application. Its value could be further increased by making it installable via Homebrew. When considering the target audience for such an app, it's important to recognize that it primarily appeals to individuals seeking substantial productivity improvements while working on their computers. Developers, who typically spend the most time in front of computers, are likely to be those primary users. They predominantly work in terminal environments and would greatly appreciate an application that offers Mouseless's functionality. From their perspective, the ability to install Mouseless through Homebrew would be a considerable enhancement.

### Proposed Solution

The solution I propose is straightforward. It involves enabling the ability to install, update, or remove mouseless through the Homebrew package manager.

**Comment by croian** [comment] 2024-12-15 07:44
Thank you for the detailed request, @ajjaic, and thank you for linking the other issue, @iotaOmicron.  This is indeed a duplicate of #3, so will close this one as such.

**Closed by croian** 2024-12-15 07:44 UTC
Labels: enhancement
