### ISSUE TITLE
Can't use Z key in Dvorak layouts

### ISSUE THREAD

**Issue by NextMerge** [croian/mouseless-issues#30] opened 2024-12-13 15:21 UTC
### mouseless version

0.2.1

### macOS version

15.2

### Other system input apps

Homerow, Superkey, Raycast

### What happened?

Continuation of https://github.com/croian/mouseless-issues/issues/4

When the overlay is active, it doesn't register any key presses on Z (which is where / is on QWERTY). Doesn't fire in both the main grid or the sub grid.

### Steps to Reproduce

- Set keyboard to Dvorak
- Use the overlay.
- Press Z (or where / is physically located)
- Nothing happens

**Comment by croian** [comment] 2024-12-13 17:57
thank you for this, NextMerge.  i've reproduced it -- will investigate and prioritize a fix 👍

**Comment by croian** [comment] 2024-12-18 05:24
fixed!  as with #39, for non-`U.S.` layouts, alt and ctrl will not work for actions/keybindings that combine with printable chars (should be fine for triggering actions aside from that though) for now.

**Comment by croian** [comment] 2024-12-18 11:37
@NextMerge not sure if my mentioning this issue causes a notification for you, but in case it doesn't -- thought I'd let you know the prerelease linked above has the fix for this issue in it if you want to try it out!

**Comment by NextMerge** [comment] 2024-12-18 18:48
Seems to work in the pre-release. You can close this issue now unless you want to wait for a proper release.

**Comment by NextMerge** [comment] 2024-12-18 18:57
Actually I just noticed that if you hold down an action (in my case ControlLeft for 'move'), all of the keys appear to be mismatched on Dvorak.

**Comment by croian** [comment] 2024-12-18 19:38
whoa, good catch, thank you for reporting.  i was expecting that (given the remaining issue mentioned earlier) alt and control would cause unexpected behavior on both the main grid and the subgrid.  but as you mention, it seems to be working when used on the subgrid, which is the more critical place for it to work -- a pleasant surprise!

perhaps i can leverage this into a full fix for the alt/ctrl stuff.  either way, thank you again for the heads up! 🙏

**Comment by NextMerge** [comment] 2024-12-18 19:47
Correction: The sub grid also seems to broken.

**Comment by croian** [comment] 2024-12-24 15:26
released in v0.2.2.  the alt and ctrl issue will be tracked in #57

**Closed by croian** 2024-12-24 15:26 UTC
Labels: bug, fixed, pending release, high priority
